---
title: "Iteration and ListCols"
author: "Mahdi Maktabi"
date: "2024-10-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```


## Here's some lists

```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample = runif(100),
  mat = matrix(1:8, nrow = 2, ncol = 4, byrow = TRUE),
  summary = summary(rnorm(100))
)

l$mat

l[["mat"]][1:3]

l[[1]]
l[[4]]
```

Make a list that's hopefully a it more useful.

```{r}
list_norm =
  list(
    a = rnorm(20, 0, 5),
    b = rnorm(20, 4, 5),
    c = rnorm(20, 0, 10),
    d = rnorm(20, 4, 10)
  )

list_norm[["a"]]
```

Let's reuse a function we wrote last time.

```{r}
mean_and_sd = function(x) {
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df =
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(out_df)
}
```

Lets use this function to take mean and sd of all samples.

```{r}
mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])
```

